// Auto-generated from CommandCode CLI 1.54.0 `--list-models` output.
// Primary ids use the CLI canonical ids; alias ids map to their canonical upstream id.
export const COMMANDCODE_MODELS = [
  { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
  { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
  { id: "deepseek/deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp" },
  { id: "deepseek/deepseek-v4-flash-fast", name: "DeepSeek V4 Flash Fast" },
  { id: "deepseek/deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash" },
  { id: "moonshotai/Kimi-K3", name: "Kimi K3" },
  { id: "moonshotai/Kimi-K2.7-Code", name: "Kimi K2.7 Code" },
  { id: "moonshotai/Kimi-K2.7-Code-Highspeed", name: "Kimi K2.7 Code Highspeed" },
  { id: "moonshotai/Kimi-K2.6", name: "Kimi K2.6" },
  { id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5" },
  { id: "z-ai/glm-5.3-flash", name: "GLM 5.3 Flash" },
  { id: "zai-org/GLM-5.3", name: "GLM 5.3" },
  { id: "zai-org/GLM-5.2", name: "GLM 5.2" },
  { id: "zai-org/GLM-5.2-Fast", name: "GLM 5.2 Fast" },
  { id: "zai-org/GLM-5.1", name: "GLM 5.1" },
  { id: "zai-org/GLM-5", name: "GLM 5" },
  { id: "MiniMaxAI/MiniMax-M3", name: "MiniMax M3" },
  { id: "MiniMaxAI/MiniMax-M2.7", name: "MiniMax M2.7" },
  { id: "MiniMaxAI/MiniMax-M2.5", name: "MiniMax M2.5" },
  { id: "xiaomi/mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
  { id: "xiaomi/mimo-v2.5", name: "MiMo V2.5" },
  { id: "Qwen/Qwen3.8-Max-0902", name: "Qwen3.8 Max 0902" },
  { id: "Qwen/Qwen3.8-Max", name: "Qwen3.8 Max" },
  { id: "Qwen/Qwen3.8-27B", name: "Qwen3.8 27B" },
  { id: "Qwen/Qwen3.8-Flash", name: "Qwen3.8 Flash" },
  { id: "Qwen/Qwen3.7-Max", name: "Qwen3.7 Max" },
  { id: "Qwen/Qwen3.7-Plus", name: "Qwen3.7 Plus" },
  { id: "Qwen/Qwen3.7-Flash", name: "Qwen3.7 Flash" },
  { id: "Qwen/Qwen3.6-Max-Preview", name: "Qwen3.6 Max Preview" },
  { id: "Qwen/Qwen3.6-Plus", name: "Qwen3.6 Plus" },
  { id: "meituan/LongCat-2.0:free", name: "LongCat 2.0 (Free)" },
  { id: "stepfun/Step-3.7-Flash", name: "Step 3.7 Flash" },
  { id: "stepfun/Step-3.5-Flash", name: "Step 3.5 Flash" },
  { id: "tencent/hy3-paid", name: "Hy3 Paid" },
  { id: "tencent/hy4-preview", name: "Hy4 Preview" },
  { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra 550B A55B" },
  { id: "thinkingmachines/inkling", name: "Inkling" },
  { id: "thinkingmachines/inkling-small", name: "Inkling Small" },
  { id: "poolside/laguna-s-2.1-free", name: "Laguna S 2.1 Free" },
  { id: "inclusionai/ling-3.0-flash-sante:free", name: "Ling 3.0 Flash Sante (Free)" },
  { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
  { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
  { id: "claude-fable-5-1", name: "Claude Fable 5.1" },
  { id: "claude-fable-5", name: "Claude Fable 5" },
  { id: "claude-opus-5", name: "Claude Opus 5" },
  { id: "claude-opus-4-8", name: "Claude Opus 4.8" },
  { id: "claude-opus-4-7", name: "Claude Opus 4.7" },
  { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5 20251001" },
  { id: "gpt-6-astra", name: "GPT 6 Astra" },
  { id: "gpt-5.6-sol", name: "GPT 5.6 Sol" },
  { id: "gpt-5.6-terra", name: "GPT 5.6 Terra" },
  { id: "gpt-5.6-luna", name: "GPT 5.6 Luna" },
  { id: "gpt-5.5", name: "GPT 5.5" },
  { id: "gpt-5.4", name: "GPT 5.4" },
  { id: "gpt-5.3-codex", name: "GPT 5.3 Codex" },
  { id: "gpt-5.4-mini", name: "GPT 5.4 Mini" },
  { id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash" },
  { id: "google/gemini-3.7-flash", name: "Gemini 3.7 Flash" },
  { id: "google/gemini-3.6-flash", name: "Gemini 3.6 Flash" },
  { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash" },
  { id: "google/gemini-3.5-flash-lite", name: "Gemini 3.5 Flash Lite" },
  { id: "google/gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite" },
  { id: "sakana/fugu-ultra", name: "Fugu Ultra" },
  { id: "meta/muse-spark-1.1", name: "Muse Spark 1.1" },
  { id: "meta/muse-spark-1.2", name: "Muse Spark 1.2" },
  { id: "meta/muse-spark-1.2-contributor", name: "Muse Spark 1.2 Contributor" },
  { id: "meta/muse-spark-1.3", name: "Muse Spark 1.3" },
  { id: "meta/muse-spark-1.3-contributor", name: "Muse Spark 1.3 Contributor" },
  { id: "xai/grok-4.5", name: "Grok 4.5" },
  { id: "xai/grok-4.6", name: "Grok 4.6" },
  { id: "claude-haiku-4-5", name: "Claude Haiku 4.5", upstreamModelId: "claude-haiku-4-5-20251001" },
];
